app/urls.py
"""
Application URL Configuration
"""
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from app.sitemaps import sitemap_config
from phone.urls import router_v1 as phone_router_v1
from user.views import LoginView

ADMIN_URL = 'admin' if settings.DEBUG else 'admin-26414607'

urlpatterns = [
    url(r'^robots\.txt$', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, sitemap_config),
    url(r'^{0}/'.format(ADMIN_URL), admin.site.urls),

    url(r'^api/v1/', include([
        url(r'^', include(phone_router_v1.urls)),
    ])),

    url(r'^login/$', LoginView.as_view(), name='account_login'),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^', include('phone.urls', namespace='phones')),
    url(r'^', include('website.urls', namespace='website')),
    url(r'^', include('user.urls', namespace='users')),
]

phone/urls.py
"""
Application url config
"""
from django.conf.urls import url
from rest_framework.routers import DefaultRouter

from phone import views
from phone import viewsets

router_v1 = DefaultRouter()
router_v1.register(r'phone', viewsets.PhoneViewSet, 'phone')
router_v1.register(r'comment', viewsets.CommentViewSet, 'comment')

urlpatterns = [

    url(r'^jaunakie-komentari/$', views.LatestCommentView.as_view(), name='latest-comments'),
    url(r'^numurs/(?P<number>[0-9]{1,8})/$', views.PhoneDetailView.as_view(), name='details'),
    url(r'^komentars/(?P<pk>\w+)/$', views.CommentProfileView.as_view(), name='comment_profile'),
    url(r'^komentet/$', views.CommentCreateView.as_view(), name='add_comment'),
    url(r'^kategorija/(?P<category>[0-9-]{1,7})/$', views.CategoryView.as_view(), name='category'),
    url(r'^kategorija/$', views.CategoryView.as_view(), name='category_index'),

]

user/urls.py
"""
Application url config
"""
from django.conf.urls import url

from user import views

urlpatterns = [
    url(r'^saglabat-epastu/$', views.EmailFillView.as_view(), name='account_fill_email'),
    url(r'^lietotajs/dzest-kontu/$', views.DeleteUserView.as_view(), name='delete'),
    url(r'^lietotajs/(?P<pk>\w+)/$', views.UserDetailView.as_view(), name='details'),
    url(r'^mani-jaunumi/$', views.PhoneDashboardView.as_view(), name='phone_dashboard'),
]

website/urls.py
"""
Application url configuration
"""
from django.conf.urls import url
from django.views.generic import TemplateView

from website import views


urlpatterns = [

    url(r'^parakstities/$', views.SubscribeToNewsView.as_view(), name='email_subscribe'),
    url(r'^informacijas-dzesana/$', TemplateView.as_view(template_name='website/agreement/takedown.html'), name='takedown'),  # noqa
    url(r'^atruna/$', TemplateView.as_view(template_name='website/agreement/agreement.html'), name='agreement'),
    url(r'^kontakti/$', views.ContactView.as_view(), name='contacts'),
    url(r'^$', views.FrontPageView.as_view(), name='front'),

]

website/models.py
"""
Application models
"""

from django.db import models
from django.template.defaultfilters import slugify


class Message(models.Model):
    """
    Message details
    """

    email = models.EmailField(max_length=200)
    body = models.TextField()

    registered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Object representation as string
        :return: string
        """
        return '{0}'.format(self.email)


class Visitor(models.Model):
    """
    Anonymous visitor profile
    """
    email = models.EmailField()

    def __str__(self):
        """
        Object representation as string
        :return: string
        """
        return self.email


class Service(models.Model):
    """
    Service description page
    """
    slug_length = 50
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=slug_length, unique=True)
    body = models.TextField(blank=True, null=True)

    def __str__(self):
        """
        Object representation as string
        :return: string
        """
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)[:self.slug_length]
        super().save(*args, **kwargs)

website/forms.py
"""
Application forms
"""

from django import forms

from website.models import Message


class ContactForm(forms.ModelForm):
    """
    Login form with email as username
    """
    class Meta(object):
        model = Message
        fields = ['email', 'body']
        widgets = {
            'email': forms.TextInput(attrs={
                'placeholder': 'Jūsu epasts',
                'class': 'form-control form-control-lg'
            }),
            'body': forms.Textarea(attrs={
                'placeholder': 'Jautājums',
                'class': 'form-control form-control-lg',
                'rows': 4,
            })
        }

website/views.py
"""
Application views
"""
from django.utils import timezone
from django.views.generic import TemplateView
from phone import models

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from website import forms
from website.models import Message, Visitor

user_model = get_user_model()


class FrontPageView(TemplateView):
    """
    Front page
    """
    template_name = 'website/front.html'

    def get_context_data(self, **kwargs):

        today = timezone.now().date()
        this_month_comments = (models.Comment.objects
                               .filter(insert_date__year=today.year, insert_date__month=today.month)
                               .exclude(author__isnull=True, legacy=True))

        data = super().get_context_data(**kwargs)
        data['last_15_users'] = user_model.objects.exclude(is_staff=True).order_by('-id')[:15]
        data['total_registered_count'] = user_model.objects.exclude(is_staff=True).count()
        data['this_month_registered'] = (user_model.objects
                                         .filter(date_joined__year=today.year, date_joined__month=today.month)
                                         .exclude(legacy=True)
                                         .count())
        data['this_month_comments'] = this_month_comments.count()
        data['this_month_numbers'] = (models.Phone.objects
                                      .filter(pk__in=this_month_comments.values_list('phone_id', flat=True))
                                      .count())
        data['last_comment'] = models.Comment.objects.exclude(author__isnull=True).last()
        data['latest_comments'] = models.Comment.objects.all().order_by('-id')[:10]
        return data


class ContactView(CreateView):
    """
    Contact page
    """
    template_name = 'website/write-us.html'
    model = Message
    form_class = forms.ContactForm

    def get_success_url(self):
        return str(reverse('website:contacts')) + '?action=ok'


class SubscribeToNewsView(CreateView):
    """
    Allow users to leave email for news
    """
    model = Visitor
    fields = ['email']
    success_url = reverse_lazy('website:front')
    template_name = 'website/blank.html'

    def form_valid(self, form):
        """
        Form submission extra actions
        :param form: form instance
        :return:
        """
        messages.info(self.request, 'You have been subscribed successfully!')
        return super().form_valid(form)

website/templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="full">
<head>
    <meta charset="UTF-8">
    <meta name="google-site-verification" content="eIlNBHJx1UN-EqXAPcUXn8WwEoBjMAKiHzhuSsBbpW8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block page_title %}Kas man zvana{% endblock %} - Latvijas telefonu grāmata</title>

    <script type="application/ld+json">
        {
            "@context": "http://schema.org",
            "@type": "WebSite",
            "name": "Kas man zvana?",
            "alternateName": "Latvijas telefonu grāmata",
            "url": "{% if request.is_secure %}https{% else %}http{% endif %}://{{ request.META.HTTP_HOST }}"
        }
    </script>

    <meta name="description" content="{% block page_description %}Noskaidro nezināmā numura iespējamo īpašnieku{% endblock %}">
    <meta name="robots" content="noarchive">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:200,300">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    {% static "css/main.css" as css %}
    {% include "website/utils/compress_css.html" with path=css %}
    <link rel="icon" href="{% static "favicon.png" %}">

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.2.3/backbone-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/js-cookie/2.0.4/js.cookie.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    {% static "js/common.js" as js %}
    {% include "website/utils/compress_js.html" with path=js %}

    {% block extra_head %}{% endblock %}

    <script>
        $(space.start);
    </script>

    {% if not debug %}
        {% static "js/counter.js" as js %}
        {% include "website/utils/compress_js.html" with path=js %}
    {% endif %}

</head>
<body>

    <div class="global-wrapper">

        <div class="picture-background">
            <div class="container">
            <div class="row padding1">
                <div class="col-md-4">
                    {% include "phone/_snippets/header-menu.html" %}
                </div>
                <div class="col-md-4 text-center">
                    {% if messages %}
                        {% for message in messages %}
                            <p style="color:#f4f4f4" class="padding05">
                                {{ message }}
                            </p>
                        {% endfor %}
                    {% endif %}
                </div>
                {% if request.user.is_authenticated %}
                    <div class="col-md-4 text-right">
                        <ol class="breadcrumb global-menu">

                            <li>{% include "phone/_snippets/user.html" with user=request.user %}</li>
                            <li>
                                <a href="{% url "users:phone_dashboard" %}">
                                    Mani jaunumi
                                </a>
                            </li>
                            <li>
                                <a href="{% url "account_logout" %}?next={{ request.path }}">
                                    Atslēgties
                                </a>
                            </li>
                        </ol>
                    </div>
                {% endif %}
            </div>
        </div>
            <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    {% block body-header %}
                        <div class="jumbotron text-center" id="front-jumbo">
                            <h1>Kas man zvana?</h1>
                            <p>Noskaidro nezināmā numura iespējamo īpašnieku</p>

                            <form class="form-inline" id="number-form" method="post" action=".">
                                <div class="form-group">
                                    <label class="sr-only" for="number">Ievadiet numuru</label>
                                    <div class="input-group">
                                        <input type="number"
                                               class="form-control input-lg"
                                               id="number"
                                               maxlength="8"
                                               placeholder="Ievadi numuru"
                                               data-title="Numuru meklētājs"
                                               data-content="Ja vēlies apskatīties citus numurus, ievadi tos šeit. Ievadei vari izmantot ciparu taustiņus"
                                                >
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-primary btn-lg">
                                                <span class="glyphicon glyphicon-earphone" style="color:#f4f4f4"></span>
                                            </button>
                                        </span>
                                    </div>
                                </div>
                            </form>
                        </div>
                    {% endblock %}
                </div>
            </div>
        </div>
        </div>

        {% block page-body %}

            <div id="wrapper">

                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div id="page-body" class="col-md-10 col-md-offset-1">
                                {% block body %}{% endblock %}
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        {% endblock %}

        <div class="container padding3">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    {% url "website:front" as link_url %}
                    {% if link_url == request.path %}
                        <span>Sākums</span>
                    {% else %}
                        <span><a href="{{ link_url }}" title="Sākums">Sākums</a></span>
                    {% endif %} |

                    {% url "phones:category_index" as link_url %}
                    <span><a href="{{ link_url }}" title="Numuri">Numuri</a></span> |

                    {% url "website:agreement" as link_url %}
                    {% if link_url == request.path %}
                        <span>Saistību atruna</span>
                    {% else %}
                        <span><a href="{{ link_url }}" title="Saistību atruna">Saistību atruna</a></span>
                    {% endif %} |

                    {% url "website:contacts" as link_url %}
                    {% if link_url == request.path %}
                        <span>Kontakti</span>
                    {% else %}
                        <span><a href="{{ link_url }}" title="Kontakti">Kontakti</a></span>
                    {% endif %}
                </div>
                <div class="col-md-8 col-md-offset-2 text-center padding2 small">
                    Atbalstām <a href="https://www.trailcams.io">trailcams.io</a>
                </div>
            </div>

        </div>



    </div>

    {% include "website/includes/cookiewarning.html" %}

    <script type="text/template" id="template-table">

        <% if (_.isEmpty(rows)){ %>
        <p><%- emptyMessage %></p>
        <% } else { %>
        <table class="table table-bordered table-hover">
            <% _.each(rows, function(row){ %>
            <tr>
                <th><%- row[1] %></th>
                <td><%- row[0] %></td>
            </tr>
            <% }); %>
        </table>
        <% } %>
    </script>

    <script type="text/template" id="template-modal">
        <div class="modal fade" id="modal" tabindex="-1" role="dialog"
             aria-labelledby="modalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"
                                aria-label="Aizvērt">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="modalLabel">
                            <%- modalTitle %>
                        </h4>
                    </div>
                    <div class="modal-body">
                        <%= modalBody %>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary btn-sm"
                                data-dismiss="modal">Aizvērt
                        </button>
                    </div>
                </div>
            </div>
        </div>

    </script>

    <div id="modal-wrapper"></div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.4/js.cookie.min.js"
            integrity="sha256-NjbogQqosWgor0UBdCURR5dzcvAgHnfUZMcZ8RCwkk8="
            crossorigin="anonymous"></script>

    {% static "js/cookies.js" as js %}
    {% include "website/utils/compress_js.html" with path=js %}

</body>
</html>

website/templates/website/front.html
{% extends "website/base.html" %}
{% load static %}

{% block body %}

    {% include "phone/_snippets/login-block.html" %}


    <div class="row {% if request.user.is_authenticated %}padding2{% endif %}">
        <div class="col-md-8">

            {% include "phone/comment/latest_comment_block.html" with object_list=latest_comments %}

        </div>

        <div class="col-md-4 text-center">

            <p class="large-icon">
                <i class="fa fa-clock-o" aria-hidden="true"></i>
            </p>
            <h2>Nepalaid neko garām</h2>
            <p>
                Seko līdzi sev interesējošiem numuriem un saņem ziņu tiklīdz mēs par tiem uzzinām kautko jaunu.
            </p>

            <p class="large-icon">
                <i class="fa fa-users" aria-hidden="true"></i>
            </p>
            <h2>Vērtē numurus</h2>
            <p>
                Ar savu balsojumu maini numuru reitingu - lai visi zinātu vai šo numuru celt vai necelt.
            </p>

            <p class="large-icon">
                <i class="fa fa-cloud-upload" aria-hidden="true"></i>
            </p>
            <h2>Verificē savu numuru</h2>
            <p>
                (Drīzumā) Verificē savu numuru un pārvaldi to, uzzini sava numura sekotājus un noskaidro kāpēc,
                publicē oficiālu kontaktinformāciju.
            </p>

            <h2 class="text-left padding1">
                Statistika
            </h2>
                <div class="text-left">
                    <p>
                        Pavisam reģistrējušies {{ total_registered_count }} lietotāji no tiem {{ this_month_registered }} šomēnes.
                    </p>
                    <p>
                        Šomēnes publicēti {{ this_month_comments }} komentāri par {{ this_month_numbers }} numuriem.
                    </p>
                </div>


            <div class="text-right">
                <a href="{% url "phones:latest-comments" %}">
                    Jaunākie komentāri
                    <i class="fa fa-caret-right" aria-hidden="true"></i>
                </a>
            </div>
        </div>
    </div>


{% if not request.user.is_authenticated %}
    <div class="row text-center padding1">

        <div class="col-md-12">
            <h1>Saņem jaunumus</h1>
            <hr>
            <p>
                Ja atstāsi mums savu epastu - varēsim paziņot par mūsu jaunumiem.
            </p>

            <form class="text-center form-inline" method="post" action="{% url "website:email_subscribe" %}" style="display: inline-block">
                {% csrf_token %}
                    <input type="email" class="form-control input-lg" id="id_email" name="email" placeholder="Tavs epasts">
                    <button type="submit" class="btn btn-primary btn-lg head">
                        Parakstīties
                    </button>
            </form>
        </div>
    </div>
    <div class="padding2"></div>
{% endif %}

{% endblock %}
{% block extra_head %}

    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>

{% endblock %}

website/templates/website/write-us.html
{% extends "website/base.html" %}
{% load i18n %}

{% block page_title %}Kontakti{% endblock %}

{% block body-header %}
    <div class="jumbotron text-center" id="front-jumbo">
        <h1>
            <a href="{{ request.path }}">
                Rakstiet mums
            </a>
        </h1>
        <p>
            {% if request.GET.action != 'ok'%}
                Jautājumi vai ieteikumi?<br>
                Sūtiet mums ziņu un mēs atbildēsim drīzākajā laikā.
            {% else %}
                Mēs saņēmām ziņu un sazināsimies tuvākajā laikā.
            {% endif %}
        </p>
    </div>
{% endblock %}

{% block body %}
        <div class="row padding4">
            <div class="col-md-6 col-md-offset-3">
                <p class="small">
                    Ja rakstiet mums par noteiktu tālruņa numuru - lūdzu neaizmirstiet
                    to minēt tekstā.
                </p>
                {% include "website/includes/form.html" with submit_text="Sūtīt" %}
            </div>

        </div>
{% endblock %}

{% block extra_head %}

    <script>
        $(function(){
            $("input[type=text], textarea").addClass("input-lg");
            $(".btn").addClass("btn-lg");
        });
    </script>

{% endblock %}