app/urls.py
"""
Application URL Configuration
"""
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from app.sitemaps import sitemap_config
from phone.urls import router_v1 as phone_router_v1
from user.views import LoginView

ADMIN_URL = 'admin' if settings.DEBUG else 'admin-26414607'

urlpatterns = [
    url(r'^robots\.txt$', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, sitemap_config),
    url(r'^{0}/'.format(ADMIN_URL), admin.site.urls),

    url(r'^api/v1/', include([
        url(r'^', include(phone_router_v1.urls)),
    ])),

    url(r'^login/$', LoginView.as_view(), name='account_login'),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^', include('phone.urls', namespace='phones')),
    url(r'^', include('website.urls', namespace='website')),
    url(r'^', include('user.urls', namespace='users')),
]

blog/urls.py
"""
Application url config
"""
from django.conf.urls import url

from blog import views

urlpatterns = [

    url(r'^publikacija/(?P<slug>[a-z0-9\-]+)/$', views.PostView.as_view(), name='post'),
    # url(r'^kategorija/(?P<category>\w\_+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^$', views.FrontPage.as_view(), name='front'),

]

blog/models.py
"""
Application models
"""
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.text import slugify


user_model = get_user_model()


class Category(models.Model):
    """
    Category details
    """
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, blank=True, null=True, unique=True)

    def __str__(self):
        """
        Object representation as string
        :return: title field contents
        """
        return self.title


class Post(models.Model):
    """
    Blog post details
    """
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, blank=True, null=True, unique=True)
    body = models.TextField(blank=True, null=True)

    categories = models.ManyToManyField('blog.Category', blank=True)

    insert_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        """
        Object representation as string
        :return: title field contents
        """
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'slug': self.slug})


class Comment(models.Model):
    """
    Comment model implementation
    """
    post = models.ForeignKey('blog.Post')
    body = models.TextField()

    # Allow to display old comments from file based engine
    legacy = models.BooleanField(default=False, editable=False)

    anonymous_session = models.CharField(max_length=200, blank=True, null=True, editable=False)
    author = models.ForeignKey(user_model, blank=True, null=True, related_name='blog_comments')
    insert_date = models.DateTimeField(blank=True, null=True, editable=False)

    def __str__(self):
        """
        Object representation as string
        :return: string
        """
        return self.body

    def save(self, *args, **kwargs):
        if not (self.pk and self.insert_date):
            self.insert_date = now()
        super().save(*args, **kwargs)

blog/views.py
"""
Application views
"""

from django.views.generic import DetailView, ListView

from blog import models


class FrontPage(ListView):
    """
    Blog front page
    """
    model = models.Post


class PostView(DetailView):
    model = models.Post
    pk_url_kwarg = 'slug'

    def get_object(self, queryset=None):
        return self.model.objects.get(slug=self.kwargs.get(self.pk_url_kwarg))

blog/templates/blog/base.html
{% extends "website/base.html" %}
{% load i18n %}

{% block body %}
    <div class="row padding4">
        <div class="col-md-8">
            {% block blog-main %}{% endblock %}
        </div>
        <div class="col-md-4">
            {% block blog-sidebar %}{% endblock %}
        </div>

    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block page_description %}
    {{ object.body|truncatechars:"300" }}
{% endblock %}

{% block page_title %}
    {{ object.title|truncatechars:"100" }}
{% endblock %}

{% block extra_head %}

    <script type="application/ld+json">
        {
            "@context": "http://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": 1,
                    "item": {
                        "@id": "{% url "website:front" %}",
                        "name": "Sākums"
                    }
                },
                {
                    "@type": "ListItem",
                    "position": 2,
                    "item": {
                        "@id": "{% url "blog:front" %}",
                        "name": "Blogs"
                    }
                },
                {
                    "@type": "ListItem",
                    "position": 3,
                    "item": {
                        "@id": "{{ request.path }}",
                        "name": "{{ object.title }}"
                    }
                }
            ]
        }
    </script>
{% endblock %}

{% block blog-main %}

    <div>
        <h1>{{ object.title }}</h1>
        <hr>

        <p class="padding1">
            <a href="{% url "blog:front" %}">Blogs</a> |
            Publicēts: {{ object.insert_date|date }}
        </p>

        <div class="padding1">
            {{ object.body|linebreaks }}
        </div>

    </div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block page_title %}
    Blogs
{% endblock %}

{% block extra_head %}

    <script type="application/ld+json">
        {
            "@context": "http://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": 1,
                    "item": {
                        "@id": "{% url "website:front" %}",
                        "name": "Sākums"
                    }
                },
                {
                    "@type": "ListItem",
                    "position": 2,
                    "item": {
                        "@id": "{% url "blog:front" %}",
                        "name": "Blogs"
                    }
                }
            ]
        }
    </script>
{% endblock %}

{% block blog-main %}

    <div>
        <h1>
            <a href="{{ request.path }}">
                Blogs
            </a>
        </h1>
        <hr>

        {% for object in object_list %}

            <div>

                <h2>
                    <a href="{{ object.get_absolute_url }}">
                        {{ object.title }}
                    </a>
                </h2>

                <div class="padding1">
                    {{ object.body|truncatechars:"300" }}
                </div>


            </div>

        {% endfor %}

    </div>

{% endblock %}