app/urls.py
"""
Application URL Configuration
"""
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from app.sitemaps import sitemap_config
from phone.urls import router_v1 as phone_router_v1
from user.views import LoginView

ADMIN_URL = 'admin' if settings.DEBUG else 'admin-26414607'

urlpatterns = [
    url(r'^robots\.txt$', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, sitemap_config),
    url(r'^{0}/'.format(ADMIN_URL), admin.site.urls),

    url(r'^api/v1/', include([
        url(r'^', include(phone_router_v1.urls)),
    ])),

    url(r'^login/$', LoginView.as_view(), name='account_login'),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^', include('phone.urls', namespace='phones')),
    url(r'^', include('website.urls', namespace='website')),
    url(r'^', include('user.urls', namespace='users')),
]

user/urls.py
"""
Application url config
"""
from django.conf.urls import url

from user import views

urlpatterns = [
    url(r'^saglabat-epastu/$', views.EmailFillView.as_view(), name='account_fill_email'),
    url(r'^lietotajs/dzest-kontu/$', views.DeleteUserView.as_view(), name='delete'),
    url(r'^lietotajs/(?P<pk>\w+)/$', views.UserDetailView.as_view(), name='details'),
    url(r'^mani-jaunumi/$', views.PhoneDashboardView.as_view(), name='phone_dashboard'),
]

user/models.py
"""
Application models
"""
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from phone import mixins


class User(mixins.HashidMixin, AbstractUser):
    """
    Application user implementation
    """
    is_banned = models.BooleanField(default=False)
    legacy = models.BooleanField(default=False)

    following_list = models.ManyToManyField('phone.Phone', blank=True)

    def get_absolute_url(self):
        return reverse('users:details', kwargs={'pk': self.get_hashid_pk()})

    def last_15_comments(self):
        return self.comment_set.all().order_by('-id')[:15]

user/forms.py
from django import forms
from user import models


class EmailForm(forms.ModelForm):

    class Meta(object):
        model = models.User
        fields = ('email',)
        widgets = {
            'email': forms.EmailInput(attrs={
                'placeholder': 'Jūsu epasts',
                'class': 'form-control form-control-lg'
            })
        }

user/views.py
"""
Application views
"""
from allauth.account import views as auth_views
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, UpdateView, ListView, DeleteView

from phone.models import Comment
from user import forms
from user import models
from user.decorators import persist_session_vars
from website import mixins


@method_decorator(persist_session_vars(['_ask']), name='dispatch')
class LoginView(auth_views.LoginView):
    pass


class PhoneDashboardView(LoginRequiredMixin, ListView):
    """
    The latest comments from the phones that user follows
    """
    model = Comment
    template_name = 'user/dashboard.html'
    paginate_by = 15
    ordering = ('-id', )

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(phone__pk__in=[f.pk for f in self.request.user.following_list.all()])
        return queryset


class UserDetailView(DetailView):
    """
    User public profile view
    """
    model = models.User
    template_name = 'user/details.html'

    def get_object(self, queryset=None):
        self.kwargs[self.pk_url_kwarg] = self.model.get_pk_from_hashid(self.kwargs.get(self.pk_url_kwarg))
        return super().get_object(queryset=None)


class EmailFillView(mixins.LoginRequiredMixin, UpdateView):
    template_name = 'user/email.html'
    model = models.User
    form_class = forms.EmailForm
    success_info = 'Paldies - jūsu epasts ir saglabāts!'

    def get_success_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')

        return reverse_lazy('website:front')

    def get_object(self, queryset=None):
        return self.model.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        """
        Default actions + save profile fields too
        :param form:
        :return:
        """
        messages.info(self.request, self.success_info)
        return super().form_valid(form)


class DeleteUserView(mixins.LoginRequiredMixin, DeleteView):
    """
    User can delete his own profile
    """
    model = models.User
    template_name = 'user/delete.html'
    success_url = reverse_lazy('website:front')

    def get_object(self, queryset=None):
        return self.request.user

user/templates/user/dashboard.html
{% extends "website/base.html" %}

{% block page_title %}Mani jaunumi{% endblock %}

{% block body %}

    <div class="row padding2">
        <div class="col-md-12">
            <div class="col-md-8">
                <h1>
                    <i class="fa fa-comments" aria-hidden="true"></i>
                    Jaunākais no sekotajiem numuriem
                </h1>
                <hr>
                {% if object_list %}
                     <div class="padding0-1">
                        {% for comment in object_list %}
                            {% if not forloop.first %}<hr>{% endif %}
                            {% include "website/includes/comment-card.html" with show_number=True %}
                        {% endfor %}
                    </div>
                {% else %}
                    <p>Pagaidām vēl nav informācijas.</p>
                {% endif %}

                <div class="padding2">
                    {% include "website/includes/pagination.html" %}
                </div>
            </div>
            <div class="col-md-4">
                <h2>
                    Mans konts
                </h2>
                <hr>
                <a href="{% url "users:delete" %}" class="padding1 btn btn-block btn-lg btn-primary">
                    Dzēst
                </a>
        </div>
    </div>

{% endblock %}

user/templates/user/delete.html
{% extends "website/base.html" %}
{% block page_title %}{% include "phone/_snippets/user.html" with user=request.user %}{% endblock %}
{% block body-header %}
    <div class="jumbotron text-center" id="front-jumbo">
        <h1>
            Vai tiešām vēlaties dzēst kontu?
        </h1>
    </div>
{% endblock %}
{% block body %}
    <div class="col-md-6 col-md-offset-3 padding2">

        <p class="padding1">Brīdinām, ka šī darbība ir neatgriezeniska.</p>

        <form role="form" action="{{ request.get_full_path }}" method="post" class="form">
            {% csrf_token %}
            <div class="form-group">
                <button type="submit" class="btn {% if btn_type %}{{ btn_type }}{% else %}btn-primary{% endif %}">
                    Dzēst
                </button>
            </div>
        </form>
    </div>

{% endblock %}

user/templates/user/details.html
{% extends "website/base.html" %}

{% block page_title %}{% include "phone/_snippets/user.html" with user=object %}{% endblock %}

{% block body-header %}
    {% if request.user.is_authenticated %}
        <div class="jumbotron text-center" id="front-jumbo">

            <div>
                {% include "website/utils/avatar.html" with size="100" avatar=user.socialaccount_set.first.get_avatar_url extra_class="img-circle" %}
            </div>

            <h1>
                <a href="{{ object.get_absolute_url }}">
                    {% include "phone/_snippets/user.html" with user=object %}
                </a>
            </h1>
            <p>Piereģistrējās {{ object.date_joined|date }}</p>
        </div>
    {% else %}
        <div class="jumbotron text-center" id="front-jumbo">
            <h1>
                <a href="{{ object.get_absolute_url }}">
                    Lai skatītu šo lapu ir jāpieslēdzas
                </a>
            </h1>
        </div>
    {% endif %}
{% endblock %}
{% block body %}
    {% if request.user.is_authenticated %}
        <div class="row padding2">
            <div class="col-md-6">
                <h1>
                    <i class="fa fa-comments" aria-hidden="true"></i>
                    Komentēja
                </h1>
                <hr>
                {% if object.last_15_comments %}
                    <div class="padding0-1">
                        {% for comment in object.last_15_comments %}
                            {% if not forloop.first %}<hr>{% endif %}
                            {% include "website/includes/comment-card.html" with from_user_page=True %}
                        {% endfor %}
                    </div>
                {% else %}
                    <p>Pagaidām vēl nav informācijas.</p>
                {% endif %}
            </div>
            <div class="col-md-6">
                <h1>
                    <i class="fa fa-comments" aria-hidden="true"></i>
                    Seko numuriem
                </h1>
                <hr>
                {% if object.following_list.all %}
                    <div class="padding0-1">
                        {% for number in object.following_list.all %}
                            <h4>
                                <a href="{{ number.get_absolute_url }}">
                                    {{ COUNTRY_PREFIX }} {{ number }}
                                </a>
                            </h4>
                        {% endfor %}
                    </div>
                {% else %}
                    <p>Pagaidām vēl nav informācijas.</p>
                {% endif %}
            </div>
        </div>
    {% else %}
        {% include "phone/_snippets/login-block.html" %}
    {% endif %}
{% endblock %}

user/templates/user/email.html
{% extends "website/base.html" %}
{% load i18n %}

{% block page_title %}Kontakti{% endblock %}

{% block body-header %}
    <div class="jumbotron text-center" id="front-jumbo">
        <h1>
            <a href="{{ request.path }}">
                Nevarējām iegūt epastu
            </a>
        </h1>
    </div>
{% endblock %}

{% block body %}
    <div class="row padding2">
        <div class="col-md-12 text-center">
            <h1></h1>
            <p>Lai pilnvērtīgi varētu lietot mūsu pakalpojumus, lūdzu ievadiet savu epasta adresi.</p>
        </div>
        <div class="col-md-6 col-md-offset-3 padding2">
            {% include "website/includes/form.html" with submit_text="Saglabāt epastu" %}
        </div>
    </div>
{% endblock %}

{% block extra_head %}

    <script>
        $(function(){
            $("input, textarea").addClass("input-lg");
            $(".btn").addClass("btn-lg");
        });
    </script>

{% endblock %}