app/urls.py
"""
Application URL Configuration
"""
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from app.sitemaps import sitemap_config
from phone.urls import router_v1 as phone_router_v1
from user.views import LoginView

ADMIN_URL = 'admin' if settings.DEBUG else 'admin-26414607'

urlpatterns = [
    url(r'^robots\.txt$', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, sitemap_config),
    url(r'^{0}/'.format(ADMIN_URL), admin.site.urls),

    url(r'^api/v1/', include([
        url(r'^', include(phone_router_v1.urls)),
    ])),

    url(r'^login/$', LoginView.as_view(), name='account_login'),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^', include('phone.urls', namespace='phones')),
    url(r'^', include('website.urls', namespace='website')),
    url(r'^', include('user.urls', namespace='users')),
]

website/urls.py
"""
Application url configuration
"""
from django.conf.urls import url
from django.views.generic import TemplateView

from website import views


urlpatterns = [

    url(r'^parakstities/$', views.SubscribeToNewsView.as_view(), name='email_subscribe'),
    url(r'^informacijas-dzesana/$', TemplateView.as_view(template_name='website/agreement/takedown.html'), name='takedown'),  # noqa
    url(r'^atruna/$', TemplateView.as_view(template_name='website/agreement/agreement.html'), name='agreement'),
    url(r'^kontakti/$', views.ContactView.as_view(), name='contacts'),
    url(r'^$', views.FrontPageView.as_view(), name='front'),

]

website/models.py
"""
Application models
"""

from django.db import models
from django.template.defaultfilters import slugify


class Message(models.Model):
    """
    Message details
    """

    email = models.EmailField(max_length=200)
    body = models.TextField()

    registered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Object representation as string
        :return: string
        """
        return '{0}'.format(self.email)


class Visitor(models.Model):
    """
    Anonymous visitor profile
    """
    email = models.EmailField()

    def __str__(self):
        """
        Object representation as string
        :return: string
        """
        return self.email


class Service(models.Model):
    """
    Service description page
    """
    slug_length = 50
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=slug_length, unique=True)
    body = models.TextField(blank=True, null=True)

    def __str__(self):
        """
        Object representation as string
        :return: string
        """
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)[:self.slug_length]
        super().save(*args, **kwargs)

website/forms.py
"""
Application forms
"""

from django import forms

from website.models import Message


class ContactForm(forms.ModelForm):
    """
    Login form with email as username
    """
    class Meta(object):
        model = Message
        fields = ['email', 'body']
        widgets = {
            'email': forms.TextInput(attrs={
                'placeholder': 'Jūsu epasts',
                'class': 'form-control form-control-lg'
            }),
            'body': forms.Textarea(attrs={
                'placeholder': 'Jautājums',
                'class': 'form-control form-control-lg',
                'rows': 4,
            })
        }

website/views.py
"""
Application views
"""
from django.utils import timezone
from django.views.generic import TemplateView
from phone import models

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from website import forms
from website.models import Message, Visitor

user_model = get_user_model()


class FrontPageView(TemplateView):
    """
    Front page
    """
    template_name = 'website/front.html'

    def get_context_data(self, **kwargs):

        today = timezone.now().date()
        this_month_comments = (models.Comment.objects
                               .filter(insert_date__year=today.year, insert_date__month=today.month)
                               .exclude(author__isnull=True, legacy=True))

        data = super().get_context_data(**kwargs)
        data['last_15_users'] = user_model.objects.exclude(is_staff=True).order_by('-id')[:15]
        data['total_registered_count'] = user_model.objects.exclude(is_staff=True).count()
        data['this_month_registered'] = (user_model.objects
                                         .filter(date_joined__year=today.year, date_joined__month=today.month)
                                         .exclude(legacy=True)
                                         .count())
        data['this_month_comments'] = this_month_comments.count()
        data['this_month_numbers'] = (models.Phone.objects
                                      .filter(pk__in=this_month_comments.values_list('phone_id', flat=True))
                                      .count())
        data['last_comment'] = models.Comment.objects.exclude(author__isnull=True).last()
        data['latest_comments'] = models.Comment.objects.all().order_by('-id')[:10]
        return data


class ContactView(CreateView):
    """
    Contact page
    """
    template_name = 'website/write-us.html'
    model = Message
    form_class = forms.ContactForm

    def get_success_url(self):
        return str(reverse('website:contacts')) + '?action=ok'


class SubscribeToNewsView(CreateView):
    """
    Allow users to leave email for news
    """
    model = Visitor
    fields = ['email']
    success_url = reverse_lazy('website:front')
    template_name = 'website/blank.html'

    def form_valid(self, form):
        """
        Form submission extra actions
        :param form: form instance
        :return:
        """
        messages.info(self.request, 'You have been subscribed successfully!')
        return super().form_valid(form)

website/templates/website/agreement/agreement.html
{% extends "website/base.html" %}

{% block page_title %}
    Lietošanas noteikumi un saistību atruna
{% endblock %}

{% block body %}
    <div class="padding3">
        <h1>Lietošanas noteikumi un saistību atruna</h1>
        <hr>
        <p class="padding0-1">
            Reģistrējoties šajā vietnē, Jūs piekrītat savu sniegto datu apstrādei Fizisko personu datu
            aizsardzības likuma izpratnē. Reģistrējoties lietotāja kontaktinformācija netiek nodota
            trešajām personām, izņemot pēc kompetento valsts pārvaldes institūciju pieprasījuma
            normatīvajos aktos noteiktajos gadījumos un kārtībā.
        </p>
        <p class="padding0-1">
            Informācijas ievietotājs atbild par ievietotās informācijas saturu, kā arī par to, ka
            informāciju neievieto citas personas vārdā.
        </p>
        <p class="padding0-1">
            Reģistrācijas laikā mēs no sociālā tīkla konta saņemam Lietotāja vārdu, uzvārdu, avataru
            kā arī dažos gadījumos epasta adresi. Ja epasta adresi nav iespējams iegūt, adrese tiks īpaši
            pieprasīta pēc reģistrācijas. Informācija tiks izmantota tikai lai lietotājam nodrošinātu
            iespējami labāku lapas lietošanas pieredzi. Vienlaikus brīdinām ka Lietotāja komentāri,
            sekotie numuri, vārds, uzvārds un sociālā tīkla avatars automātiski publicēsies lietotāja
            publiskajā profila lapā.
        </p>
        <p class="padding0-1">
            Informācija (t.sk. komentāri) ar nepieņemamu saturu tiks dzēsti, autoram tiks bloķēta pieeja lapai,
            normatīvajos aktos noteiktajos gadījumos informācija tiks nodoti kompetentajām valsts pārvaldes
            institūcijām (t.sk. tiesībsargājošām iestādēm).
        </p>
        <p class="padding0-1">
            Jebkāda veida nesaskaņota reklāma tiks dzēsta. Izņēmums - saite, kas papildina informāciju vai diskusiju.
        </p>
        <p class="padding0-1">
            Jebkura informācija var tikt dzēsta, nesniedzot nekādus paskaidrojumus.
        </p>
        <p class="padding0-1">
            Jebkāda veida nesaskaņota reklāma (vai līdzīga rakstura informācija) tiks dzēsta, izņemot saites,
            kas papildina informāciju vai sniedz pienesumu diskusijai.
        </p>
        <p class="padding0-1">
            Administrators šos noteikumus var mainīt bez brīdinājuma.
        </p>
        <p class="padding0-1">
            Jūs varat jebkurā laikā pieprasīt dzēst savu kontu atsūtot mums pieprasījumu.
        </p>
        <p class="padding0-1">
            <a href="{% url "website:takedown" %}">
              Lūdzu izlasiet pirms pieprasiet dzēst citu sniegto informāciju!
            </a>
        </p>
    </div>
{% endblock %}

website/templates/website/agreement/takedown.html
{% extends "website/base.html" %}

{% block page_title %}Saistību atruna{% endblock %}

{% block body %}
    <div class="padding3">
        <h1>Lūdzu izlasiet pirms pieprasiet dzēst informāciju!</h1>
        <hr>
        <p class="padding0-1">
            Šīs vietnes saturs ietver pilnīgi visus skaitļus no <a href="/numurs/00000000/">00000000</a> līdz
            <a href="/numurs/99999999/">99999999</a>. Jebkāda sakritība ar Jūsu tālruņa numuru ir tikai
            sagadīšanās, kas administratoram neuzliek nekādus pienākumus un nerada nekādas saistības.
        </p>
        <p class="padding0-1">
            Skaitlis bez papildus identificējošām norādēm nevar tikt uzskatīts par personas datiem Fizisko
            personu datu aizsardzības likuma izpratnē. Ne skaitlis, ne alfabēta burts nevar ekskluzīvi piederēt
            nedz jums nedz arī kādai citai personai.
        </p>
        <p class="padding0-1">
            Ja jūs nevēlaties uzsvērt skaitļa saistību ar savu personu - nekomentējiet. Taupiet gan savu gan mūsu
            laiku.
        </p>
        <p class="padding0-1">
            Ar cieņu - administrācija!
        </p>
    </div>

{% endblock %}